Update web-app-dev.yaml

diff --git a/.github/workflows/web-app-dev.yaml b/.github/workflows/web-app-dev.yaml
--- a/.github/workflows/web-app-dev.yaml
+++ b/.github/workflows/web-app-dev.yaml
@@ -83,7 +83,25 @@ jobs:
       - name: Build Docker Image
         run: |
           cd web-app && docker build -t $GKE_REGION-docker.pkg.dev/$GCP_PROJECT/$GKE_REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
+      
+      # Step 5: Run Docker Scout Analysis
+      - name: Run Docker Scout Analysis
+        run: |
+          docker scout cves $GKE_REGION-docker.pkg.dev/$GCP_PROJECT/$GKE_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
 
+      # Step 6: Push image if Scout passes (no high severity vulnerabilities)
+      - name: Check and Push Image
+        id: scout-check
+        run: |
+          result=$(docker scout cves $GKE_REGION-docker.pkg.dev/$GCP_PROJECT/$GKE_REGISTRY/$IMAGE_NAME:$GITHUB_SHA --output json | jq '.advisories | map(select(.severity == "high")) | length')
+          if [ "$result" -gt 0 ]; then
+            echo "High severity vulnerabilities found. Failing the build."
+            exit 1
+          else
+            echo "No high severity vulnerabilities found. Proceeding with push."
+            cd web-app && docker push $GKE_REGION-docker.pkg.dev/$GCP_PROJECT/$GKE_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
+          fi
+          
       - name: Push Docker Image to GCR
         run: |
           cd web-app && docker push $GKE_REGION-docker.pkg.dev/$GCP_PROJECT/$GKE_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
